#define NAME_SIZE 256
#define WSIZE_DEFAULT 1
#define FILE_SIZE 65536
#define MAX_ARGS_LENGTH 8
#define BUFFER_SIZE 32768
#define MAX_CLIENT_SIZE 5

#define CONNECTION_REQUEST 0
#define CONNECTION_REPLY_SUCCESS 1
#define CONNECTION_REPLY_FAIL 2
#define CONNECTION_REGISTER 3
#define COMMAND_LINE_REQUEST 4
#define COMMAND_LINE 5
#define COMMAND_LINE_RESULT 6
#define QUIT_REQUEST 7
#define QUIT_REPLY 8
#define QUIT_ALL_REQUEST 9